version: '2.4'
services:
  grounded-sam2:
    image: grounded-sam2:latest
    privileged: true
    build:
      context: ../segmentation/Grounded-SAM-2-zeroshop
      dockerfile: Dockerfile
      shm_size: '2gb'
      args:
        - USE_CUDA=1
        - TORCH_ARCH=7.0;7.5;8.0;8.6+PTX
    shm_size: '2gb'
    network_mode: "host"
    runtime: "nvidia"
    volumes:
      - /dev/bus/usb:/dev/bus/usb
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      #- ../segmentation/Grounded-SAM-2-zeroshop/:/code
      #- ../segmentation/Grounded-SAM-2-zeroshop/torch_cache:/root/.cache/torch
      - ../datasets:/code/datasets
    environment: 
      - DISPLAY
      - QT_X11_NO_MITSHM=1
      - NVIDIA_DRIVER_CAPABILITIES=all
    command: bash -c "python process_real_object_dataset_docker.py --dataset_path /code/datasets/ycbv_real_subset --prompt 'object in the middle.';
                      chmod -R 777 /code/datasets
                      exec bash" 
    stdin_open: true
    tty: true 